/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasoswing05v;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Cetecom
 */
public class CrearUsuario extends javax.swing.JFrame {

    private List<Usuario> userList;
    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        
        initComponents();
        getRegiones();
        rbInformatica.setSelected(true);
        userList = new ArrayList<Usuario>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCategoriaEmpleado = new javax.swing.ButtonGroup();
        labelNombreUsuario = new javax.swing.JLabel();
        textFiledNombreUsuario = new javax.swing.JTextField();
        rbSecretaria = new javax.swing.JRadioButton();
        rbGerencia = new javax.swing.JRadioButton();
        rbInformatica = new javax.swing.JRadioButton();
        cbRegiones = new javax.swing.JComboBox<>();
        botonGuardarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNombreUsuario.setText("Nombre Usuario");

        bgCategoriaEmpleado.add(rbSecretaria);
        rbSecretaria.setText("Secretaría");

        bgCategoriaEmpleado.add(rbGerencia);
        rbGerencia.setText("Gerencia");

        bgCategoriaEmpleado.add(rbInformatica);
        rbInformatica.setText("Informática");

        cbRegiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        botonGuardarUsuario.setText("Guardar");
        botonGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardarUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbInformatica)
                        .addComponent(rbGerencia)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNombreUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textFiledNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rbSecretaria)
                        .addComponent(cbRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUsuario)
                    .addComponent(textFiledNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbSecretaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbGerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbInformatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(botonGuardarUsuario)
                .addGap(53, 53, 53))
        );

        rbSecretaria.getAccessibleContext().setAccessibleName("Secretaría");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarUsuarioActionPerformed
        String nombreUsuario = textFiledNombreUsuario.getText();
        String categoria = "";
        String region = cbRegiones.getSelectedItem().toString();
        if(rbGerencia.isSelected()){
            categoria = rbGerencia.getText();
        }else if(rbSecretaria.isSelected()){
            categoria = rbSecretaria.getText();
        }else if(rbInformatica.isSelected()){
            categoria = rbInformatica.getText();
        }
        Usuario user = new Usuario(nombreUsuario, categoria, region);
        
        userList.add(user);
        JOptionPane.showMessageDialog(null, "Usuario " + nombreUsuario + " ha sido creado con éxito!");
    }//GEN-LAST:event_botonGuardarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }
    
    private void getRegiones(){
        List<String> regionList = new ArrayList<String>();
        regionList.add("Arica");
        regionList.add("Coquimbo");
        regionList.add("Metropolitana");
        regionList.add("Maule");
        regionList.add("Osorno");
        cbRegiones.setModel(new DefaultComboBoxModel<String>(regionList.toArray(new String[0])));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCategoriaEmpleado;
    private javax.swing.JButton botonGuardarUsuario;
    private javax.swing.JComboBox<String> cbRegiones;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JRadioButton rbGerencia;
    private javax.swing.JRadioButton rbInformatica;
    private javax.swing.JRadioButton rbSecretaria;
    private javax.swing.JTextField textFiledNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
